const usersData = [
    { id: '1', time: '2012/01/01', content: 'Member', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Staff', listcustomer: 'Banned', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Admin', listcustomer: 'Inactive', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/03/01', content: 'Member', listcustomer: 'Pending', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/21', content: 'Staff', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/01', content: 'Member', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Staff', listcustomer: 'Banned', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Admin', listcustomer: 'Inactive', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/03/01', content: 'Member', listcustomer: 'Pending', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/21', content: 'Staff', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/01', content: 'Member', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Staff', listcustomer: 'Banned', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Admin', listcustomer: 'Inactive', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/03/01', content: 'Member', listcustomer: 'Pending', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/21', content: 'Staff', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/01', content: 'Member', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Staff', listcustomer: 'Banned', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Admin', listcustomer: 'Inactive', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/03/01', content: 'Member', listcustomer: 'Pending', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/21', content: 'Staff', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/01', content: 'Member', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Staff', listcustomer: 'Banned', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/02/01', content: 'Admin', listcustomer: 'Inactive', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/03/21', content: 'Staff', listcustomer: 'Active', companyemail: 'comemail@gmail.com' },
    { id: '1', time: '2012/01/01', content: 'Member', listcustomer: 'Pending', companyemail: 'comemail@gmail.com' }
]

export default usersData

/*
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' }
*/

