const usersData = [
    { id: '1', name: '2012/01/01', status: 'Member', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Staff', createDate: 'Banned', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Admin', createDate: 'Inactive', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/03/01', status: 'Member', createDate: 'Pending', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/21', status: 'Staff', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/01', status: 'Member', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Staff', createDate: 'Banned', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Admin', createDate: 'Inactive', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/03/01', status: 'Member', createDate: 'Pending', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/21', status: 'Staff', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/01', status: 'Member', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Staff', createDate: 'Banned', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Admin', createDate: 'Inactive', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/03/01', status: 'Member', createDate: 'Pending', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/21', status: 'Staff', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/01', status: 'Member', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Staff', createDate: 'Banned', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Admin', createDate: 'Inactive', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/03/01', status: 'Member', createDate: 'Pending', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/21', status: 'Staff', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/01', status: 'Member', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Staff', createDate: 'Banned', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/02/01', status: 'Admin', createDate: 'Inactive', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/03/21', status: 'Staff', createDate: 'Active', companyemail: 'comemail@gmail.com', updateDate: "", id_tem: "" },
    { id: '1', name: '2012/01/01', status: 'Member', createDate: 'Pending', companyemail: 'comemail@gmail.com, updateDate:"", id_tem:""' }
]

export default usersData

/*
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' },
, status: 'o', idcompany: '2', idtemplate: '3', idcustomer: '4' }
*/